### PR TITLE
Convert mongodb_instance to resource

### PR DESCRIPTION
**Pull request by luishdez**
Source: https://github.com/edelight/chef-mongodb/pull/194

### CODE REVIEW

**Comment by rex** [comment]
Yikes. @josephholsten I feel like this is multiple pull requests. 

Also, I saw you added `.travis.yml`. Aren't we already running TravisCI on `master`?

**Comment by josephholsten** [comment]
@rex I'm rebasing this now. It's safe to say this will probably be 2 PRs, plus at least one cleanup one.

**Comment by josephholsten** [comment]
closing in favor of #44

**Comment by josephholsten** [comment]
poking to annoy slack

**Pull request closed without merging**
