### PR TITLE
Fix mongodb user/group on RHEL

### PR DESCRIPTION
**Pull request by huyanhvn**
With mongodb user/group set to be "mongod" on RHEL, the cookbook fails out of the box, looking for 'mongod' user/group that are not there, as well as failing to start mongodb because /var/[lib/log/run]/mongodb are owned by mongodb:mongodb. When I changed these attributes to 'mongodb' the cookbook works out the box.

### CODE REVIEW

**Comment by djmbm** [comment]
This PR is incorrect. That user/group is correct for older releases (Pre EL7), and so just needs wrapped in an if statement. I'll be forking this repo, as it is unmaintained, and maintaining it as part of my job's organization. The forked repo will have this issue fixed. As we're using this in a business sense, it will also be somewhat more reliably maintained (unlike this repo that was forked from the original and promptly seems abandoned)

**Comment by triccardi-systran** [comment]
@djmbm would you be interested in being a contributor/maintainer of this fork?
The goal of this fork was to gather the community that spread after the original project was abandoned.
This fork seems abandoned but it just lacks someone to work on it. Let's not fork it again if possible.

(Speaking for myself I do have a professional interest on this and have some small patchs I should merge back here when I find some time...)

Ping @josephholsten @jmccann @luishdez @rex

**Comment by djmbm** [comment]
@triccardi-systran That would be a good solution also. I have already forked the repo so that all members of my team may work on it, but by being added back to this project as well I can help keep it going. Not all of our changes would be suitable to backport into this repo anyway.

**Comment by djmbm** [comment]
PR #103 is the 'correct' fix for this issue, as it maintained EL6 and Fedora < 20 compatibility, this PR should be closed.

**Comment by triccardi-systran** [comment]
@djmbm I somehow am not "owner" on chef-brigade anymore (not sure why... it would be nice to get it back...) so I can't add you as member or owner of chef-brigade for now. Let's wait for some owner to get my previous ping.

**Comment by triccardi-systran** [comment]
Closing in favor of #103.

**Comment by josephholsten** [comment]
@triccardi-systran sorry about that, you're an owner now!

**Pull request closed without merging**
