### PR TITLE
fix creating user bug for custom host and port

### PR DESCRIPTION
**Pull request by luishdez**
Source: https://github.com/edelight/chef-mongodb/pull/359

### CODE REVIEW

**Comment by luishdez** [comment]
I think this one is clear, @zarry @josephholsten just pinging to confirm

**Comment by luishdez** [comment]
I'think this one is clear, @zarry @josephholsten just pinging to confirm

**Comment by zarry** [comment]
Only potential issue I see is I don't see that we have any default value for ['mongodb']['config']['host'].  Should someone use this without setting that I would expect it to error out?  Does a sane default of localhost make sense?  Does this get set somewhere else that I am missing?

**Comment by luishdez** [comment]
Yep! Adding a default makes sense to me

The ruby client > 2.0.0 ( that I hope we update someday ) uses a different way to create connections concatenating host and port "host:port" so If we update without a default value it will break… 

I guess  MongoClient use its default value "localhost" when receives false or null and same for port…

I'll add the default and notes to README before making the merge

**Comment by josephholsten** [comment]
To be clear, the value in `default['mongodb']['config']['bind_ip']` (default `0.0.0.0`) is almost certainly not what we want this default to be, yes?

I'm not sure we want to add a `default['mongodb']['config']['host']` since that is meaningless. Should the default just be set in the provider? eg
```ruby
(@new_resource.connection['config']['host'] || '127.0.0.1'), # default to localhost if unset
```

**Comment by luishdez** [comment]
bind_ip is where mongo allow connections … by default 0.0.0.0 that is the same of all IPs/interfaces, but if someone sets Eg: `195.28.13.1` that could be a remote server. Mongo will only allow connections from that Ip, so if we use bind_ip here, it will try to connect to `195.28.13.1` another machine…

And if we create `default['mongodb']['config']['host'] ` it will end up in the `mongo.conf` file and Host is not a valid option for mongo.conf
https://github.com/chef-brigade/mongodb-cookbook/blob/dc5836318a27331f605f264d946931927dd26bb8/libraries/mongodb_config_helpers.rb 

I'd go with 127.0.0.1 set directly, because the recipe is executed always within the node that is trying to create users, localhost…

```ruby
Mongo::MongoClient.new(
    '127.0.0.1',
    @new_resource.connection['config']['port'],
     :connect_timeout => 15,
     :slave_ok => true
)
```

**Comment by rex** [comment]
I agree with @luishdez. There's no use case that I can think of in which the recipe will be run on a machine that is not intended to run MongoDB, which makes me feel comfortable using the local loopback interface `127.0.0.1`.

**Comment by zarry** [comment]
:+1:

**Comment by rex** [comment]
@zarry @luishdez I updated the resource host to `127.0.0.1` and merged it.

**Pull request merged**
